name: Deploy to VM
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 152.42.250.99
          username: kimang
          key: ${{ ROTHA_SERVER_KEY }}
          port: 8000
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd devops-cadt-2
            git pull
            pm2 restart devops-test